### ISSUE TITLE
request_slides_of_the_paper

### ISSUE THREAD

**Issue by liu666666** [ZhaofanQiu/pseudo-3d-residual-networks#1]
Thanks for your great work and nice sharing! @ZhaofanQiu 
Is there the slides of the paper publicly available? Thanks!

**Comment by ZhaofanQiu** [comment]
Thanks for your interest :)
Actually, I don't have the slides specifically for this paper, but you can refer to my supervisor Tao's Tutorial at ACM Multimedia [https://www.microsoft.com/en-us/research/wp-content/uploads/2017/10/Tao-Mei-Intelligent-Video-Analysis-ACMMM-2017-Pub.pdf](url). My work is part of this tutorial. Thanks.

**Comment by liu666666** [comment]
Thank you very much!
