### ISSUE TITLE
How about Kinetics evaluation?

### ISSUE THREAD

**Issue by rimchang** [ZhaofanQiu/pseudo-3d-residual-networks#11]
How about Kinetics evaluation?
I can't find Kinetics evaluation in paper.

**Comment by ZhaofanQiu** [comment]
Hi, the P3D paper is an early work before Kinetics release. The P3D on kinetics is still an ongoing work. The model and evaluation results will be updated after the full experiments. Here I only gave the roughly trained models on Kinetics, and the top1 accuracy is 72.1% (frame) & 61.2% (flow) on Kinetics validation.
Best.

**Comment by rimchang** [comment]
Thank you very much!
