### ISSUE TITLE
Could I train your code after  install caffe-ms?

### ISSUE THREAD

**Issue by shanYanGuan** [ZhaofanQiu/pseudo-3d-residual-networks#2]
I don't want add the layer into caffe-bvlc. So directly installing caffe-ms dose work.Am I right?

**Comment by ZhaofanQiu** [comment]
The Caffe version I used is not based on Caffe-ms. It is converted from Linux-version Caffe-BVLC to windows platform by myself.
So if you want to use Caffe-ms, you also need to add these new layers since these layers are not implemented in Caffe-ms yet, I think. Thanks :)

**Comment by shanYanGuan** [comment]
I see.Thanks for your patient and meticulous to answer!
