### ISSUE TITLE
Question about P3D ResNet-50 in UCF101

### ISSUE THREAD

**Issue by KeyKy** [ZhaofanQiu/pseudo-3d-residual-networks#5]
```
In the training stage, we set each mini-batch as 128 frames/clips.
```
128 frames equal to 8 clips (16 frames/clip). Whether these 8 clips come from one video or from 8 videos?

**Comment by ZhaofanQiu** [comment]
Actually, we set 128 frames as mini-batch for ResNet50 and 128 clips as mini-batch for P3D ResNet50.
And for each mini-batch, the 128 clips are randomly from different videos.
Best.

**Comment by KeyKy** [comment]
Thanks! Another question, How do you pick 16 frames?
```
0,1,2,3,4, ..., 16 (interval==1) or  0,2,4,6,...,30 (interval==2) or ..
```

**Comment by ZhaofanQiu** [comment]
We only try consecutive frames (interval==1).
This setting may also be affected by the fps when extracting the frames. Here, we choose ffmpeg toolbox to extract all the frames.

**Comment by KeyKy** [comment]
How many clips do you sample in UCF101 P3D resnet-50. Maybe I miss something, I found the number of sport1m
```
Specifically, we randomly sample 20 clips from each video and adopt a single center crop per
clip.
```

**Comment by ZhaofanQiu** [comment]
In this experiment, we uniformly sampled 25 frames for ResNet-50 and 20 clips for P3D ResNet-50.
This is not very clear in the paper. Thanks for pointing out.
